# Generated by Django 4.2.8 on 2024-05-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('notice', '공지사항'), ('question', '질문게시판'), ('review', '리뷰게시판'), ('all', '전체')], default='all', max_length=20),
        ),
    ]
