# Generated by Django 4.2.8 on 2024-05-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saving',
            field=models.ManyToManyField(blank=True, related_name='saving_joined', to='savings.savingproducts'),
        ),
    ]
